In [1]:
import numpy as np
from decimal import *
getcontext().prec = 2000

In [2]:
# корни многочлена
roots = np.linspace(1, 2021, num=2021, endpoint=True, dtype='int')
roots

array([   1,    2,    3, ..., 2019, 2020, 2021])

In [3]:
# промежуточные значения по x (без целых чисел)
x_arr = np.linspace(1.0000001, 2021, num=1000000, endpoint=False)
y_arr = np.zeros_like(x_arr)

In [4]:
# получение суммы значение (1/(x-1)), где i = (1, .., 2021)
for i in range(y_arr.shape[0]):
    y_arr[i] = (1 / (x_arr[i] - roots)).sum()

y_arr

array([ 9.99999181e+06,  4.86833356e+02,  2.39323646e+02, ...,
       -1.56818176e+02, -2.39329773e+02, -4.86857862e+02])

In [5]:
# получение индексов значений по X в которых производная близка к 0
x_zero = np.isclose(y_arr, np.zeros_like(y_arr), atol=0.00001).nonzero()
x_zero

(array([293769, 706231], dtype=int64),)

In [6]:
# вывод значений по X в которых производная равна 0
print(f'x1: {x_arr[x_zero[0][0]]}, x2: {x_arr[x_zero[0][1]]}')

x1: 594.413380070623, x2: 1427.586620029377


In [7]:
# аккумулируем значения каждого множителя (x - i) / 2021, где i = от 1 до 2021
x1 = Decimal(x_arr[x_zero[0][0]])
x2 = Decimal(x_arr[x_zero[0][1]])
dec_number1 = Decimal(1)
dec_number2 = Decimal(1)
for i in range(1, 2022):
    dec_number1 *= (x1 - i) / 2021
    dec_number2 *= (x2 - i) / 2021

print(dec_number1)
print(dec_number2)

-1.125043551475353398109239338E-1409
1.125043551475914883941508584E-1409


In [8]:
# вывод значения
dec_number1.as_tuple()

DecimalTuple(sign=1, digits=(1, 1, 2, 5, 0, 4, 3, 5, 5, 1, 4, 7, 5, 3, 5, 3, 3, 9, 8, 1, 0, 9, 2, 3, 9, 3, 3, 8), exponent=-1436)

In [10]:
# переводим значения digit в целое число
int_number1 = int(''.join([str(x) for x in list(dec_number1.as_tuple()[1])]))
int_number2 = int(''.join([str(x) for x in list(dec_number2.as_tuple()[1])]))

In [11]:
# умножаем int_number на 2021^2021 (потому что до этого мы делили на 2021)
big_number1 = int_number1 * (2021**2021)
big_number2 = int_number2 * (2021**2021)

In [12]:
# переводим big_number в строку, откидываем последние числа (столько, сколько указано в exponent для числа dec_number)
extremum1 = int(str(big_number1)[:-(abs(dec_number1.as_tuple()[2]) + len(str(int_number1)))])
extremum2 = int(str(big_number2)[:-(abs(dec_number2.as_tuple()[2]) + len(str(int_number2)))])

In [13]:
if extremum1 > extremum2:
    print(f'Минимальное значение многочлена в точке x = {x_arr[x_zero[0][1]]} равно:\ny = {extremum2}\nКол-во знаков y: {len(str(extremum2))}')
    print(f'Максимальное значение многочлена в точке x = {x_arr[x_zero[0][0]]} равно:\ny = {extremum1}\nКол-во знаков y: {len(str(extremum1))}')
    print(f'Амплитуда значений Ymax-Ymin = {extremum1-extremum2}\nКол-во знаков Ymax-Ymin: {len(str(extremum1-extremum2))}')
else:
    print(f'Минимальное значение многочлена в точке x = {x_arr[x_zero[0][0]]} равно:\ny = {extremum1}\nКол-во знаков y: {len(str(extremum1))}')
    print(f'Максимальное значение многочлена в точке x = {x_arr[x_zero[0][1]]} равно:\ny = {extremum2}\nКол-во знаков y: {len(str(extremum2))}')
    print(f'Амплитуда значений Ymax-Ymin = {extremum2-extremum1}\nКол-во знаков Ymax-Ymin: {len(str(extremum2-extremum1))}')

Минимальное значение многочлена в точке x = 594.413380070623 равно:
y = 3987392146408411505028501385415583313391228976613654806352946541464126765174868905099536449930141744895539653533653956414942194734842784361742433670630952125453523206526374600032784834466312224525463072857109665868322154635413098980959123248989447868217518842939333915907645024369309167718693999335449017784721317447974107563113340381767462191569117148102990201668700531415386066101038501678941544830326530883077136650417657848669794050673514277329285889033172576947841560454317691564721381705362294870027988873574383555965250101397943208527899253370566807210879120889759543137257570031421637493933234393785362298096398223388888984289183625659344526391861363399592874477925090665753177740113037392184330237874291696022998277789055026399622261566984807010163213635397635212530357033126570481634119114754329511204411158158603363415372768409320939222068561968375929635027446803242288240418989892003132253367817032607202690041790448